dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    packages: libnss3-tools

language: node_js
node_js:
  - 8

git:
  depth: 1

branches:
  only:
    - master
    - next

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

before_script:
  - export WITH_LOG=true
  - export LIGHTHOUSE_CHROMIUM_PATH=`which google-chrome-stable`

script:
  - yarn test
